project_id = "hquxitmtsaexcbqjjzbu"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.verify-id-document]
    verify_jwt = false
